### PR TITLE
Add Python tutorials YouTube playlist

### PR DESCRIPTION
**Pull request by netwarex**
Add Python for Data Science and Analytics Tutorial Series Youtube Playlist

### CODE REVIEW

**Comment by netwarex** [comment]
Hi @romulomourao! I'm not sure if you aware of the PR, so I just tagged you :) Please let me know if everything is fine with the PR :)

**Comment by romulomourao** [comment]
Hey @netwarex ...sorry about that, I was kinda busy these days, anyway..I merged it now

**Comment by netwarex** [comment]
No problem! Thanks ;)

**Comment by netwarex** [comment]
@romulomourao Somehow only this one not showing up on the a Hacktoberfest dashboard :( Can you please add hacktoberfest-approved label?

I'm really appreciate that!

**Pull request merged**
